// js/core/GameInitializer.js
// Utility that wires a BaseGame subclass instance to the page.
// Loaded by game-handler.php after BaseGame.js, before the game file.
//
// Usage in each game file:
//   document.addEventListener('DOMContentLoaded', () => {
//       window.game = new MyGame();
//       window.game.init();
//   });
//
// The global `game` reference is used by inline onclick handlers in
// the HTML generated by BaseGame._rebuildGameCard() and showLevelSelection().

// No code needed here beyond documentation — BaseGame.init() handles
// everything. This file exists so game-handler.php can load it and
// the original GameInitializer reference in algebra.js still resolves.

class GameInitializer {
    // Legacy static helper kept for backwards compatibility with algebra.js
    static init(gameInstance) {
        window.game = gameInstance;
        gameInstance.init();
    }
}